name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "51.38.32.11"
        username: "ubuntu"
        password: "6aAuThuvZfFq"
        port: "22" 
        script: |
          hostname
          lxc launch ubuntuclean testgit -s test
          lxc list
          lxc delete testgit --force
          lxc list
          
